repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
      - id: black
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        files: ^source/
        types: [file, python]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.1"
    hooks:
      - id: bandit
        entry: bandit
        exclude: ^tests/
        verbose: true
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        always_run: true
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
