repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E501,W503,E203,E712"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.4.4
    hooks:
    - id: pip-audit
      args: ["-r", "requirements.txt", "--ignore-vuln", "PYSEC-2022-237"]
  - repo: https://github.com/awslabs/git-secrets
    rev: 99d01d5
    hooks:
      - id: git-secrets
        name: Git Secrets
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        always_run: true
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
