[tool.black]
line-length = 120
target-version = ["py37", "py38", "py39"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
  | cdk.out
  | codeseeder.out
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
src_paths = ["src"]
py_version = 39
skip_gitignore = false

[tool.commitizen]
name = "cz_conventional_commits"
version = "{{cookiecutter.version}}"
tag_format = "$version"
