[tool.black]
line-length = 124
target-version = ["py37", "py38", "py39"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
  | cdk.out
  | codeseeder.out
)/
'''

[tool.isort]
profile = "black"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"

[tool.bandit.assert_used]
skips = ['*_test.py', '*/test_*.py']
